services:

    frontend:
        build:
            context: ./frontend/react/ecommerce-project
            dockerfile: Dockerfile
        
        container_name: rsm_frontend
        restart: unless-stopped

        ports:
         - "3000:80"
            
        depends_on:
           - backend
            
    
    backend:
        build:
            context: ./backend/rsm_backend
            dockerfile: Dockerfile

        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ASPNETCORE_HTTP_PORTS: 8080
            ConnectionStrings__DefaultConnection: >-
                Host=${DB_HOST};
                Port=${DB_PORT} ;
                Database=${DB_NAME};
                Username=${DB_USER};
                Password=${DB_PASSWORD}
            Resend__ApiKey: ${Resend_Api_Key}
            GuestJwt__Secret: ${GUEST_JWT_SECRET}
            GuestJwt__Issuer: ${GUEST_JWT_ISSUER}
            GuestJwt__Audience: ${GUEST_JWT_AUDIENCE}
            GuestJwt__ExpirationMinutes: ${GUEST_JWT_EXPIRATIONMINUTES}
            Frontend__Origin: ${FRONTEND_ORIGIN}

        ports:
            - "8080:8080"

        depends_on:
            db:
                condition: service_healthy

    
    db:
        image: postgres:17-bookworm
        container_name: rsm_postgres_db
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "henr9423", "-d", "rsm_ecommerce_db"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        environment:
            POSTGRES_USER: henr9423
            POSTGRES_PASSWORD: fhq89hfh
            POSTGRES_DB: rsm_ecommerce_db

        ports:
            - "5433:5432"

        volumes:
            - pgdata:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: unless-stopped
        container_name: postgres-adminer-rsm
        depends_on:
          - db
        ports:
            - 8087:8080
        environment:
            - ADMINER_DEFAULT_SERVER=db

    pgadmin:
        image: dpage/pgadmin4
        container_name: postgres-pgadmin-rsm
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy
        ports:
         - "8086:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: root@local.com
            PGADMIN_DEFAULT_PASSWORD: root
            
        volumes:
            - pgadmin_data:/var/lib/pgadmin

volumes:
    pgdata:
    pgadmin_data: